- hosts: all
  tags: vim
  environment: "{{ proxy_env }}"
  vars:
    username: root
    vim_version: 8.1.2269
    gcc_version: 8.4.0
  tasks:
     - shell: /usr/bin/gcc --version | head -1 | awk '{print $NF}'
       register: gcc_installed_version

     - shell: /usr/bin/vim --version | grep IMproved | awk '{print $5}'
       register: vim_installed_version

     - name: 安装vim和相关依赖  # {{{ | 确保vim版本在8.1.2269及以上
       package:
         name: "{{ item }}"
         state: latest
       with_items:
         - vim
         - golang-go
         - make
         - cmake
         - clang
         - python3
         - g++-8

     - block:
         - name: 升级vim版本-添加源
           apt_repository:
               repo: jonathonf/vim
           ignore_errors: yes

         - name: 安装最新版vim
           package:
             name: vim
             state: latest
       when: vim_installed_version.stdout is version(vim_version,"<")

     - block:
         - name: 设置g++环境变量
           shell: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
           ignore_errors: yes
       when: gcc_installed_version.stdout is version(gcc_version,"<")

     - name: 准备vim插件文件夹
       file:
         path: ~{{ username }}/.vim/{{ item }}
         state: directory
         owner: "{{ username }}"
         group: "{{ username }}"
         mode: 0755
       with_items:
         - plugged
         - autoload
         - bundle
       # }}}

     - name: 安装vim-plug插件管理器 # {{{
       stat:
         path: ~{{ username }}/.vim/autoload/plug.vim
       register: plug_vim

     - get_url:
         url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
         dest: ~{{ username }}/.vim/autoload/plug.vim
         mode: 0644
         owner: "{{ username }}"
         group: "{{ username }}"
       when: plug_vim.stat.exists == false
       # }}}

     - stat: # {{{ | 安装airline插件
         path: ~{{ username }}/.vim/plugged/vim-airline
       register: vim_airline

     - stat:
         path: ~{{ username }}/.vim/plugged/vim-airline-themes
       register: vim_airline_themes

     - git:
         repo: https://github.com/vim-airline/vim-airline
         dest: ~{{ username }}/.vim/plugged/vim-airline
         clone: yes
         update: yes
       when: vim_airline.stat.exists == false

     - git:
         repo: https://github.com/vim-airline/vim-airline-themes
         dest: ~{{ username }}/.vim/plugged/vim-airline-themes
         clone: yes
         update: yes
       when: vim_airline_themes.stat.exists == false
       # }}}

     - stat: # {{{ | 安装自动提示插件
         path: ~{{ username }}/.vim/bundle/Vundle.vim
       register: vundle_vim

     - stat:
         path: ~{{ username }}/.vim/bundle/YouCompleteMe
       register: youcompleteme

     - git:
         repo: https://github.com/VundleVim/Vundle.vim.git
         dest: ~{{ username }}/.vim/bundle/Vundle.vim
         clone: yes
         update: yes
       when: vundle_vim.stat.exists == false

     - git:
         repo: https://github.com/Valloric/YouCompleteMe.git
         dest: ~{{ username }}/.vim/bundle/YouCompleteMe
         clone: yes
         update: yes
         recursive: yes
       ignore_errors: yes
       when: youcompleteme.stat.exists == false

     - shell: ~{{ username }}/.vim/bundle/YouCompleteMe/install.py --all
       ignore_errors: yes
       when: youcompleteme.stat.exists == false
       # }}}

     - name: 配置vim # {{{
       template:
         src: files/vim/vimrc.j2
         dest: "~{{ username }}/.vimrc"
         owner: "{{ username }}"
         group: "{{ username }}"
         mode: 0644
        # }}}
